platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'ReactiveCocoa', '2.2.3'
pod 'ReactiveViewModel', '0.2'
pod 'JDStatusBarNotification', '1.4.7' #for status bar dropdown notifications
pod 'MRProgress', '0.3.1'
pod 'VTAcknowledgementsViewController', '0.8' #for adding licenses and library links
pod 'JazzHands', '0.0.3' #for intro tours
pod 'ECSlidingViewController', '2.0.1' #sliding menu app framework
pod 'RevMob', '7.4.1' #advertising
pod 'Parse-RACExtensions', '0.0.3' #installs Parse and Facebook-iOS-SDK
pod 'Reachability', '3.1.1'
pod 'JVFloatLabeledTextField', '0.0.5' #for animating placeholder text above line in textfields
pod 'SIAlertView', '1.3' #alertview with block syntax and colored buttons
pod 'STPTransitions' #for animated transitions between view controllers
pod 'FXBlurView', '1.5.3' #for blurring overlay view in realtime
pod 'Nimbus/Core', '= 1.0.0'
pod 'Nimbus/AttributedLabel', '= 1.0.0'
pod 'TRVSMonitor'


# if permissions error, try:
# sudo sudo chown -R knight Pods
# in the project folder