platform :ios, '7.0'

# ignore all warnings from all pods
inhibit_all_warnings!

pod 'ReactiveCocoa', '2.2.4'
pod 'ReactiveViewModel', '0.2'
pod 'JDStatusBarNotification', '1.4.7' #for status bar dropdown notifications
pod 'MRProgress', '0.4.1' #for modal spinner views
#pod 'VTAcknowledgementsViewController', '0.9' #for adding licenses and library links
#pod 'JazzHands', '0.0.3' #for intro tours
pod 'RevMob', '7.4.5' #advertising
pod 'Parse-RACExtensions', '0.0.3' #installs Parse and Facebook-iOS-SDK
pod 'Reachability', '3.1.1'
pod 'JVFloatLabeledTextField', '0.0.6' #for animating placeholder text above line in textfields
pod 'SIAlertView', '1.3' #alertview with block syntax and colored buttons
pod 'STPTransitions' #for animated transitions between view controllers
#pod 'FXBlurView', '1.5.3' #for blurring overlay view in realtime
pod 'Nimbus/Core', '= 1.2.0'
pod 'Nimbus/AttributedLabel', '= 1.2.0'
pod 'TRVSMonitor', '0.0.3' #for unit testing async operations
pod 'CrashlyticsFramework', '2.1.7'
pod 'MBPullDownController', '1.1.1' #to display the hidden find bar/call taxi
pod 'Mantle', '1.4.1'
pod 'Foursquare-API-v2', '1.4.4'

# if permissions error, try:
# sudo chown -R knight Pods
# in the project folder